### ISSUE TITLE
If I want to modfiy Entitys , but I want keep most of data， what should I do?

### ISSUE THREAD

**Issue by CheneyWong** [ponyorm/pony#123]
I'am findding a easyway to expand apps， even it is rarely .

**Comment by kozlovsky** [comment]
Sorry for delay. Currently you need to execute ALTER TABLE command manually. It is not that hard if the modification is just adding new column. The simplest way to do it is in the admin interface of your DBMS. You can also execute the command using the method of `Database` object: `db.execute(sql)`.

We plan to add migration tool in September, this tool will be able to do everything automatically.

**Comment by kozlovsky** [comment]
This is the example how modifying of the database can be done via script:

Let's say we have a database with a single entity `Person`, defined in the following way inside the module `models.py`:

```python
# models.py - the module with entity definitions
from pony import orm

db = orm.Database('sqlite', 'example.db', create_db=True)

class Person(db.Entity):
    name = orm.Required(str)
    age = orm.Required(int)
```

We use this module in the main program file:

```python
# main.py - the main program
from models import *
db.generate_mapping(create_tables=True)

...  # other stuff
```

Now let's say we modified `Person` entity and added `phone` attribute to it:

```python
# models.py - the module with entity definitions
from pony import orm

db = orm.Database()

class Person(db.Entity):
    name = orm.Required(str)
    age = orm.Required(int)
    phone = orm.Optional(str)
```

Now we need to change the `Person` table correspondingly. At first we need to know what is the definition of a new column. If you designed entities using our [ER diagram editor site](http://editor.ponyorm.com), you can just switch to the tab with the SQL for the specific database and found new column definition inside the CREATE TABLE command.

If you don't use the diagram editor, you can get CRATE TABLE command by calling `generate_create_script` method of the `DBSchema` object:

```python
>>> from models import *
>>> db.generate_mapping(check_tables=False)
>>> print db.schema.generate_create_script()
CREATE TABLE "Person" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "age" INTEGER NOT NULL,
  "tel" TEXT NOT NULL
)
```

You can see that the new column defined as `"tel" TEXT NOT NULL`. Although the `tel` attribute is defined as `Optional`, the column has `NOT NULL` constraint, because by default Pony represents missing string values as empty strings.

Now you can open a database admin interface and issue command:
```sql
ALTER TABLE "Person" ADD COLUMN "tel" TEXT NOT NULL DEFAULT '';
```
For SQLite you can run this command in a program [SQLiteSpy](http://www.yunqa.de/delphi/doku.php/products/sqlitespy/index) or some other similar program.

Note that you need to specify the default value if the column is defined as `NOT NULL`.

As an alternative you can write a script which will execute the `ALTER TABLE` command. Such script can look like this:

```python
from models import *
db.execute('''
    ALTER TABLE "Person" ADD COLUMN "tel" TEXT NOT NULL DEFAULT ''
''')
db.commit()
```

When you run this script it should perform modification of the database, and after that the `generate_mapping` method should work without errors.

When we'll implement the migration tool it will compare the tables in the database and the entities in the program and will perform all necessary modifications automatically.
