### ISSUE TITLE
Missing `id` in SELECT for grouped queries

### ISSUE THREAD

**Issue by julianwachholz** [ponyorm/pony#125]
When selecting some rows from an aggregate query with a `JOIN` Pony forgets to include the `id` column of the joined table.

Example Query:

```
highscores = select(
    (p.name, sum(r.points for r in p.rounds_solved), count(p.rounds_solved))
    for p in Player
    if len(p.rounds_solved) > 0
).order_by(-2)
```

This will yield the following SQL which is invalid in PostgreSQL:

```
SELECT "p"."name", (
    SELECT coalesce(SUM("r"."points"), 0)
    FROM "round" "r"
    WHERE "p"."id" = "r"."solver"
    ), COUNT(DISTINCT "round-1"."id")
FROM "player" "p"
  LEFT JOIN "round" "round-1"
    ON "p"."id" = "round-1"."solver"
GROUP BY "p"."name"
HAVING COUNT(DISTINCT "round-1"."id") > 0
ORDER BY 2 DESC
```

And the error:

```
pony.orm.dbapiprovider.ProgrammingError: subquery uses ungrouped column "p.id" from outer query
LINE 4:     WHERE "p"."id" = "r"."solver"
```

Adding `p.id` to the selected columns will fix it:

```
SELECT "p"."id", "p"."name", (
    SELECT coalesce(SUM("r"."points"), 0)
    FROM "round" "r"
    WHERE "p"."id" = "r"."solver"
    ), COUNT(DISTINCT "round-1"."id")
FROM "player" "p"
  LEFT JOIN "round" "round-1"
    ON "p"."id" = "round-1"."solver"
GROUP BY "p"."id", "p"."name"
HAVING COUNT(DISTINCT "round-1"."id") > 0
ORDER BY 3 DESC
```

**Comment by kozlovsky** [comment]
Hi Julian! Thanks for reporting the error!

I don't think that adding `id` column automatically is the correct way of solving this problem, because adding new column to the `GROUP BY` section completely changes the grouping result.

It is absolutely valid if someone want to group table rows just by the `name` column, even if the `name` column is not unique. In this case, all rows with the same player's name are grouped together, even if these rows belong to several players who have the same name. This is the valid query, and may be useful in some situations (but probably not in yours).

If Pony will add player id to the `GROUP BY` section automatically it will completely change the query meaning (assuming non-unique player names), because in that case each group will now include rows for one player only. It may be dangerous to do such change automatically, because the programmer may be unaware that the query now groups not all players with the same name, but each player separately.

Probably Pony should detect a situation which can lead to this error and raise exception which error message should suggest to the programmer to add the necessary column manually.

Regarding your original query, I think that you can fix it by adding `p.id` to the result part of the generator manually:

```python
select((p.id, p.name, sum(...
```

In that case the `p.id` column will be added to `GROUP BY` section. For your query this is correct, because different player probably cannot have the same name, and the grouping will not be changed.

Another way is to select player itself instead of a player name:

```python
select((p, sum(...
```

Then Pony will group rows by `p.id` (without the `p.name`), and in your case the grouping will remain the same.

Theoretically, in your case Pony can recognize that the `p.name` column is already unique for each user, and in that case it can add `p.id` to the `GROUP BY` section safely without changing the grouping. I suspect that such a check may be somewhat nontrivial to implement, but i think that eventually it may be nice to have.

**Comment by julianwachholz** [comment]
Thank you for this thorough explanation. I might have some rusty understandings of SQL `GROUP BY` but I get the gist of it.

My `name` column is indeed unique, I've since solved my problem here by selecting the `p` Player directly instead of just their name, as you suggested.

I'll leave this open for a future option of detecting a `unique` column for grouped queries.
