### ISSUE TITLE
Need to understand how Required(bool, default=TRUE) works

### ISSUE THREAD

**Issue by igor-rossetti** [ponyorm/pony#166]
Hello,
I was playing with sqlite and I thought  that

`closed=Required(bool, default=TRUE)`

 was translate to 

`closed	BOOLEAN NOT NULL DEFAULT 'True'`

but I found by the `sql_debug(True)` that it was only

`closed	BOOLEAN NOT NULL `.

I wonder what I miss. Someone could explain the desidered result? 

Thank you a lot!

**Comment by kozlovsky** [comment]
As SQLite lacks specific `BOOLEAN` type, in the database Pony represents `True` and `False` Python values as `1` and `0`. This is more convenient than using textual values `'True'` and `'False'`, because with integer values it is possible to write `WHERE closed` instead of `WHERE closed = 'True'`.

I noticed that you use `TRUE` as a default value. I'm guessing that this variable is defined as following: `TRUE = 'True'`. In that case you should not use `bool` as an attribute  type, use `str` instead.

In order to add `DEFAULT` clause to a column description, currently it is necessary to manually specify `sql_default` option:

```python
    closed = Required(bool, default=True, sql_default='1')
    # or:
    closed = Required(str, default=TRUE, sql_default="'True'")
```
The `sql_default` value is a string with SQL expression which is directly injected into `CREATE TABLE` command. Notice that I wrapped string value `'True'` in an additional quotes.

Currently Pony does not automatically add `DEFAULT` clause to a column definition and processes `default` values in Python instead. Maybe we should automatically translate `default` to `sql_default` for constant values too, but we cannot do it in a more complex situations. This is because a default expression is not always a constant, it may be arbitrary python function as well. For example:

```python
import uuid
from pony.orm import *

db = Database('sqlite', ':memory:')

class MyEntity(db.Entity):
    code = Required(uuid.UUID, default=uuid.uuid4)
```

As SQLite does not know anything about `uuid4` function, we need to generate such values in Python.

**Comment by igor-rossetti** [comment]
Hi!
I can only say a big "Thank You" for the very instructive reply.
