### ISSUE TITLE
Too many caching in core.Query?

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#168]
```python
from pony.orm import *

db = Database()

class TestPost(db.Entity):
    name = Required(str, 128, autostrip=False)

db.bind('sqlite', ':memory:')
db.generate_mapping(create_tables=True)
# sql_debug(True)

with db_session:
    for i in range(1, 101):
        post = TestPost(name='post {}'.format(i))
        post.flush()

with db_session:
    query = TestPost.select()
    print(query[30:33])  # [31, 32, 33]

with db_session:
    query = TestPost.select()
    len(query)  # 100
    # Offopic: how about to make query.__len__() equivalent of query.count()?
    print(query[30:33])  # [1, 2, ..., 99, 100]???

with db_session:
    query = TestPost.select()
    print(query[95:98])  # [96, 97, 98]
    print(query[30:33])  # [96, 97, 98]???

```

**Comment by kozlovsky** [comment]
Fixed. Regarding making `query.__len__()` equivalent of `query.count()`: currect behavior of `query.__len__()` is more efficient if you need to do iteration over resulted objects, one less query is sent to the database. Also, `count()` does not guarantee that the number will actually match the number of objects, because most databases does not provide serializable isolation level by default, and another transaction can insert/delete rows after the count is executed..

**Comment by socketpair** [comment]
Так и не понял в чём баг

**Comment by kozlovsky** [comment]
@socketpair the bug manifested itself when a different slicing was applied to the same query instance. The result of first slicing was cached and used for all subsequent slices. The correct behavior is to issue another SQL query with different LIMIT...OFFSET parameters.
