### ISSUE TITLE
Is there any way to dynamically create an entity class?

### ISSUE THREAD

**Issue by 892768447** [ponyorm/pony#213]
Is there any way to dynamically create a table name?
Recently, I want to dynamically create a table with year suffix, but i have no idea, can any one help me, thanks!
like this:

class User(db.Entity):
    # 自增id
    id = PrimaryKey(int, auto=True)
    # 用户
    user = Required(str, unique=True)

Class_Dict = {}

def getClass(hashid):
    if hashid not in Class_Dict:
        cls = type(
            "User" + str(hashid),
            (User,), {}
        )
        Class_Dict[hashid] = cls
        return cls
    return Class_Dict[hashid]

but i got an error: pony.orm.dbapiprovider.InternalError: (1054, "Unknown column 'user.classtype' in 'field list'")

**Comment by kozlovsky** [comment]
I don't think this is a good practice to create separate entity for each year. Why do you want to do this?

You was able to dynamically create entity, but if you entity uses inheritance, the additional discriminator column should present in a table. I think that when you first time launches your application, it didn't define any dynamic entity, and `classtype` column remains non created.

In order to avoid the error you can define discriminator column manually:

```python
class User(db.Entity):
    # 自增id
    id = PrimaryKey(int, auto=True)
    # 用户
    user = Required(str, unique=True)
    # 继承处理的特殊列
    classtype = Discriminator(str)
```

**Comment by 892768447** [comment]
oh，thanks for your help，i try this。
