### ISSUE TITLE
generate_mapping error

### ISSUE THREAD

**Issue by stsouko** [ponyorm/pony#251]
I use postgres schemas. 

    _table_ = (schema, 'molecule')

and then I run `generate_mapping(create_tables=True)` on existing db with tables I receive:

> DBSchemaError: Table "db_data"."molecule" cannot be created, because table "molecule" (with a different letter case) already exists in the database. Try to delete "molecule" table first.

but without schemas this works fine.

**Comment by newJerseyan** [comment]
Unfortunately, I am experiencing the same issue.

I adhered to schema support format illustrated in the examples in the official ponyorm repo (https://github.com/ponyorm/pony/blob/orm/pony/orm/examples/university1.py on line 33).

There is no problem with creating the tables for the first time but whenever this script is run again, e.g., when importing it into another script which populates the database, it crashes.
Manually checking would be a (although cumbersome) alternative, the expected behavior of the generate_mapping(create_tables=True) method (as far as I have interpreted it) is to only try generating the tables if they do not yet exists. 

I am grateful for any suggestions on how to solve this elegantly. Thanks!

**Comment by stsouko** [comment]
currently I use separate function in setup file of my app for map generation on first run.

**Comment by christosR** [comment]
any update on this? I have the same issue with postgres

**Comment by christosR** [comment]
when using _table_ = (schema, 'tablename')
line 58 in dbschema.py compares a tuple with a string and the comparison fails. 
The second element of the tuple is the actual table-name in the correct case.

**Comment by kozlovsky** [comment]
Hi, sorry for the long delay with response. I fixed the code, now tables with explicitly specified schema name should be created without errors

**Comment by christosR** [comment]
thank you, will give it a shot

**Comment by christosR** [comment]
are you going to release anytime soon?

**Comment by kozlovsky** [comment]
I hope I can do release tomorrow

**Comment by christosR** [comment]
that would be great! ty

**Comment by pieterdb** [comment]
Any chance we can get that release? I'm having the same issue. 
Thanks!

**Comment by kozlovsky** [comment]
Tomorrow's day will be dedicated to the release

**Comment by pieterdb** [comment]
Thanks for the update ! 
I'm keeping my fingers crossed for that release then.
