### ISSUE TITLE
How to do coalesce on aggregation?

### ISSUE THREAD

**Issue by dekoza** [ponyorm/pony#293]
I want to annotate results with the last time a page was displayed and then sort in descendant order. Unfortunately when there is no such date I get None which messes the order by juping in front.
When I tried to use `max(i.created) if i.created else datetime(1970,1,1)` I got `Expression is too complex to decompile` error

**Comment by sashaaero** [comment]
Can you show full query line, please?

**Comment by kozlovsky** [comment]
Thank you for reporting! I agree that Pony should support `coalesce` function, and we just added support of it in b63634b8 and ccbcf8ce. Starting from release 0.7.3 you will be able to write
```python
coalesce(max(i.created), datetime(1970, 1, 1))
```

Regarding `Expression is too complex to decompile` error, that arises because at this moment Pony decompiler cannot handle if-expression bytecode. In order to use if-expressions, you need to pass generator text as a string. By the way, you query looks incorrect: if-expression should be inside `max` function:
```python
max(i.created if i.created is not None else datetime(1970, 1, 1))
```

Also, I'm not sure the query is logically correct. When you use aggregation, you need to have some grouping, and it is not clear to me what you want to place to `GROUP BY` section of your SQL query

**Comment by dekoza** [comment]
That is awesome news! Thank you! Please disregard the second part, I was indeed using Pony in the wrong way ;)
