### ISSUE TITLE
Storage engine can not be set per table

### ISSUE THREAD

**Issue by ml31415** [ponyorm/pony#295]
MySQL allows to define different storage engines per table like innodb, myisam, or especially for MariaDB, columnstorage. Also, supporting the COMMENT keyword for CREATE would be great. Looks like there is currently no way to specify this with pony. I'd sponsor a $200 bug bounty for a timely fix.

https://dev.mysql.com/doc/refman/5.6/en/storage-engine-setting.html
https://mariadb.com/kb/en/library/columnstore-create-table/

**Comment by kozlovsky** [comment]
Ok, I think we can fix it tomorrow

**Comment by kozlovsky** [comment]
Now you can specify table options using the following syntax:

```python
class MyEntity(db.Entity):
    id = PrimaryKey(int)
    foo = Required(str)
    bar = Optional(int)

    _table_options_ = {
        'ENGINE': 'InnoDB',
        'TABLESPACE': 'my_tablespace',
        'ENCRYPTION': "'N'",
        'AUTO_INCREMENT': 10
    }
```

Pony doesn't know anything about table options, it just append them to CREATE TABLE command.

Regarding `columnstorage` engine, it is possible that we need suppress index creation for that table, because that engine does not allow explicit indexes. Please report if you will have some problems.
