### ISSUE TITLE
Aggregation Operation in JSON Column

### ISSUE THREAD

**Issue by Menda0** [ponyorm/pony#301]
Hi I am trying to execute the following query:

`select((o.label,avg(o.properties["Output"])) for o in Object if o.repid.id == 2 and o.object_class.name == "Application Service")`

However I an getting the following error:

> Function 'AVG' expects argument of numeric type, got 'Json' in avg(o.properties['Throughput'])

I tried to execute an aggregation operation in non JSON columns with no problem.

Does pony orm not support aggregation operation in JSON columns or there is any way do solve this problem?

Regards,
Marco Mendão

**Comment by kozlovsky** [comment]
Hi, I think we need to fix it. Currently it is not working because Pony does not know the type of JSON expression - is it `int`, `str` or something else, and may be different in different rows. Probably we can implicitly case such JSON expressions to `float`, it should be what user expects in most cases.

Also, we need to add support of `float` function to allow explicit conversion of any expression to the `float` type
