### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'seeds'

### ISSUE THREAD

**Issue by NiklasRosenstein** [ponyorm/pony#314]
I've been able to create a small example to reproduce this issue. It seems to be a combination of using an Entity subclass and accessing member functions.

#### Error

```
Traceback (most recent call last):
  File "test.py", line 64, in <module>
    print(list(list_location(['com.example'])))
  File "test.py", line 48, in <genexpr>
    return (x.as_tuple() for x in Location.get_by_path(path).children)
  File "test.py", line 35, in as_tuple
    if not self.parent:
  File "<string>", line 2, in __get__
  File "C:\Users\niklas\.virtualenvs\fatartifacts-LoWBpE4v\lib\site-packages\pony\utils\utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "C:\Users\niklas\.virtualenvs\fatartifacts-LoWBpE4v\lib\site-packages\pony\orm\core.py", line 2099, in __get__
    value = attr.get(obj)
  File "C:\Users\niklas\.virtualenvs\fatartifacts-LoWBpE4v\lib\site-packages\pony\orm\core.py", line 2111, in get
    seeds = obj._session_cache_.seeds[val._pk_attrs_]
AttributeError: 'NoneType' object has no attribute 'seeds'
```

#### Code

```python
from pony import orm
db = orm.Database('sqlite', ':memory:')


class Location(db.Entity):
  name = orm.Optional(str)
  parent = orm.Optional('Location', reverse='children')
  children = orm.Set('Location', cascade_delete=True)
  orm.composite_index(name, parent)

  @classmethod
  def get_root(cls) -> 'Location':
    root = cls.get(name='', parent=None)
    if not root:
      root = cls(name='', parent=None)
    return root

  @classmethod
  def get_by_path(cls, path):
    current = cls.get_root()
    for i in range(len(path)):
      current = cls.get(name=path[i], parent=current)
      if not current:
        raise ValueError(path)
    return current

  @classmethod
  def from_path(cls, path):
    parent = cls.get_by_path(path[:-1])
    entity = cls(name=path[-1], parent=parent)
    return entity

  def as_tuple(self):
    if not self.parent:
      return (None, self.name)
    return (self.parent.as_tuple(), self.name)


# XXX Remove this subclass and the error does not happen.
class Object(Location):
  pass


@orm.db_session
def list_location(path):
  # XXX Or don't use as_tuple() here.
  return (x.as_tuple() for x in Location.get_by_path(path).children)

@orm.db_session
def create_location(path):
  Location.from_path(path)

db.generate_mapping(create_tables=True)
with orm.db_session:
  Location.get_root()


# XXX Or use this context manager.
# with orm.db_session:
print(list(list_location([])))
create_location(['com.example'])
create_location(['com.example', 'foobar'])
print(list(list_location(['com.example'])))
```

Unfortunately, none of the ways above to prevent the issue are an option in my use case. :( Any idea how to fix this?

**Comment by NiklasRosenstein** [comment]
This is the method that the AttributeError is raised in (Line 2111):

https://github.com/ponyorm/pony/blob/ee73a6d4f0461fa39eae8b03ef354480ad89062d/pony/orm/core.py#L2104-L2113

The condition above that line explicitly checks if there's any subclasses fo the `val` entity, so this is definitely related to entity subclasses. Looks like a bug to me. Can anyone confirm?

**Comment by NiklasRosenstein** [comment]
Adding to the condition 

```python
if val is not None and attr.reverse and val._subclasses_ and val._status_ not in ('deleted', 'cancelled'):
```

the part

```python
and obj._session_cache_:
```

make it work.

**Comment by kozlovsky** [comment]
Thanks for reporting!

> Is that an appropriate fix?
Yes, it is correct fix. But I want to explain what is really happened:

1) When you work with Pony, all operations with objects should took place inside a `db_session`. During the `db_session` Pony maintains a cache with loaded objects. This way Pony avoids repeated loading of objects which were already loaded in current `db_session`. So, you need to wrap function with `@db_session` decorator or use `db_session` context manager. If several sequential actions are part of the same logical sequence, it is more efficient to wrap them in a single `db_session`.

2) the last line of your test example is
```python
print(list(list_location(['com.example'])))
```

In this line you execute `list_location` function which is wrapped with `@db_session` decorator. But the function returns a generator object:

```python
@orm.db_session
def list_location(path):
  return (x.as_tuple() for x in Location.get_by_path(path).children)
```

In Python, generators are evaluated lazily. That is, when the function returns a generator object, it is not fully executed yet. Specifically, `x.as_tuple()` expression is not evaluated yet. But when we returned from the function, `db_session` decorator thinks that all work with the database is already done, and starts clearing the session cache. At this moment, Pony assumes that no new operations will be performed with previously retrieved objects and clears some internal structures in order to simplify work for Python garbage collector.

After that, `list` function call placed outside of `list_location` function receives a generator and starts performing `next` calls on it. The generator starts executing `x.as_tuple()` expression and fail with error because some internal structures were already cleared.

At this moment Pony allows reading previously loaded attributes of objects even after `db_session` was finished, because many users still rely on that, but maybe in the future we will switch to "strict" default mode when all working with objects outside of `db_session` is forbidden (currently it is possible to enforce "strict" mode by specifying `strict=True` option to `db_session`). The benefits of strict mode is more aggressive garbage collection, slightly faster performance and lower memory usage.

Returning to you code: I think it is better to replace generator with list comprehension. List comprehensions are evaluated eagerly, and this way we can guarantee that all evaluation will take place inside `db_session`:

```python
@orm.db_session
def list_location(path):
  return [x.as_tuple() for x in Location.get_by_path(path).children]
```

But after the fix I commited, previous version of code should works too
