### ISSUE TITLE
Can't get json attribute from Set

### ISSUE THREAD

**Issue by xunto** [ponyorm/pony#315]
I have a model like this:
```python
class Pool(db.Entity):
    pool_name = Required(str, unique=True)

    builds = Set(lambda: Build)

class Build(db.Entity):
    data = Required(Json)

    pools = Set(lambda: Pool)
```

but when I do something like:
```python
pool.builds.data
```

I get:
```python
    def distinct(iter):
        d = defaultdict(int)
        for item in iter:
>           d[item] = d[item] + 1
E           TypeError: unhashable type: 'TrackedDict'
```

Tested on master branch(orm)

**Comment by kozlovsky** [comment]
Hi Valentine, what type are you expecting to get?

**Comment by xunto** [comment]
@kozlovsky set with json's. It usually works that way.

**Comment by kozlovsky** [comment]
We cannot return a set of json's, because json value is subclass of dict and cannot be item of set. Probably for such attributes we can indeed return a list of dicts. I think the result elements should be not a TrackedDict instances, but just plain dicts, and their subsequent modifications should not be reflected in models.

**Comment by xunto** [comment]
@kozlovsky yeah, sounds good. I forgot that you can't store dicts in set (even though I felt that something is wrong about it).
