### ISSUE TITLE
How to use time as attribute type?

### ISSUE THREAD

**Issue by divrikli** [ponyorm/pony#319]
Hello,

I can not figure out, how I can use time as attribute type for an entity (https://docs.ponyorm.com/entities.html#attribute-data-types). I want to save the utc timestamp from time.time(). Is it possible to save the utc timestamp to a time attribute or I have to use an another attribute type? Unfortunately I could not find an example for it. :(

Evren

**Comment by kozlovsky** [comment]
"time.time()" does not return the utc timestamp, see for example [this StackOverflow question](https://stackoverflow.com/questions/16554887/does-pythons-time-time-return-a-timestamp-in-utc)

The `time` type in Python stores only a local time of day, without year, month or day of month. In order to represent UTC time in Pony (include year, month, day, hours, minutes. etc) you can use `datetime` type. You can get UTC time using `datetime.utcnow()` call:

```python
import time, datetime
from pony.orm import *

db = Database()

class Person(db.Entity):
    id = PrimaryKey(int)
    name = Required(str)
    date_of_birth = Required(datetime.date)
    wake_up_alarm = Optional(datetime.time)
    updated_at = Required(datetime.datetime,
                          default=datetime.datetime.utcnow)

sql_debug(True)

bind('sqlite', ':memory:')
generate_mapping(create_tables=True)

with db_session:
    p = Person(id=1, name='John Smith',
               date_of_birth=datetime.date(1990, 1, 1),
               wakeup_time=datetime.time(7, 30))

with db_session:
    p = Person[1]
    p.wake_up_alarm = datetime.time(8, 15)
    p.updated_at = datetime.datetime.utcnow()
```
