### ISSUE TITLE
to_dict()

### ISSUE THREAD

**Issue by paulyim** [ponyorm/pony#328]
when call Entity.to_dict(), LongStr column will lose

**Comment by chisvi** [comment]
Use `to_dict(with_lazy=True)`. 

`to_dict()` method does not retrieve fields with lazy option set to `True`, as explained in [docs](https://docs.ponyorm.com/api_reference.html?highlight=to_dict#Entity.to_dict).

`LongStr` attributes are declared with option `lazy=True` [by default](https://docs.ponyorm.com/api_reference.html?highlight=lazy#cmdoption-arg-lazy), so you must use option `with_lazy` when calling `to_dict()` method in order to retrieve lazy attributes.
