### ISSUE TITLE
Know if an object is already commited?

### ISSUE THREAD

**Issue by NiklasRosenstein** [ponyorm/pony#353]
Is there a way to know if an object is already commited to the database? If using an auto incrementing primary key, I can check if the object's id is not None. But I can't use them in this case.

My specific use case is that I have a thread that processes items in a queue. These items are IDs of rows in the database. It can happen that an object/row is created and not commited before it is enqueued, resulting the thread attempting to retrieve the object when it is not actually been added to the database, yet.

This is a programming error that I would like to catch early, that is when the item is put into the queue rather than when the thread tries to access it.

Is there a way to know if the object is already commited?

The following does not work because the current `db_session()` knows about the object even if it is not commited.

```python
def put(self, build):
  if Build.get(id=build.id) is None:
    raise RuntimeError('commit the object before enqueuing it')
  # ...
```

**Comment by kozlovsky** [comment]
Hi, at first I want to say that there are two ways to organize a queue: inside a database and outside of it. If you keep a queue inside the database (as a separate table), and put an object id into the queue in the same transaction as you create the object, the object id will be visible to another thread only when object is already committed.

If you store the queue outside of database, you should put object id into the queue after commit only. You can use the following pattern:

```python
@db_session
def create_object():
    obj = MyObject(...)
    flush()  # force insert operation to obtain id value
    obj_id = obj.id
    commit()
    queue.put(obj_id)

def process_queue():
    obj_id = queue.get()
    with db_session:
        obj = MyObject[obj_id]  # the obj is committed for sure
        process_object(obj)
```

Alternatively, the function that generates object may use the next pattern:

```python
@db_session
def create_object():
    obj = MyObject(...)
    return obj.id

def create_object_and_populate_queue():
    obj_id = create_object()
    # the transaction is already finished implicitly
    queue.put(obj_id)
```

The drawback of storing queue outside of database is a small chance that the process will be terminated after the object was committed to the database, but before the queue was processed, so the object will stay unprocessed. But that chance is probably small, and you can find such objects later.

Regarding to your question, pony does not have a way to determine if object was committed. In principle it is possible to have some `committed` flag in objects, but I think it may be not too efficient to have such a flag in every object, because it will require re-visiting all loaded objects after commit in order to set the flag. Most users does not need such functionality.

Maybe in the future we can implement `after_commit` hook similar to current `after_insert` hook, and re-visit objects only if the `after_commit` hook is defined.

**Comment by NiklasRosenstein** [comment]
Hi @kozlovsky, thanks a lot for your input. The object is put into the queue from inside a `@db_session` wrapped Flask route. As I mentioned before, I would prefer to just use `pony.orm.commit()` before adding it to the queue and warn if that commit hasn't happened.

Anyway, actually it's a good idea to just use a database query to retrieve the next item and not use a separate in-memory queue at all. Thanks for the tip!
