### ISSUE TITLE
SQLite and case sensitivity

### ISSUE THREAD

**Issue by spl0k** [ponyorm/pony#367]
Since version 0.7.4, `LIKE`s on SQLite are case sensitive. Is there a way to revert to the old behaviour other than adding `.lower()` or `.upper()` everywhere in the code?

I want to use case insensitive comparison and pattern matching, and my database schemas are designed accordingly (tables aren't created by _pony_) using `unicode_ci` collations on MySQL, `citext` on PostgreSQL and `COLLATE NOCASE` on SQLite.
Since 0.7.4, the `COLLATE NOCASE` is ignored on expressions using `LIKE` while it's working as expected on comparisons.

**Comment by kozlovsky** [comment]
Hi Alban!

Our goal is maximum possible compatibility between different databases, so the same Pony query returns the same result in all databases.

The default LIKE implementation in SQLite differs from another databases. By default in SQLite `LIKE` is case-insensitive for ASCII symbols, but is case-sensitive for Unicode symbols. In other databases `LIKE` is case-sensitive for all symbols, except when special case-insensitive collation is specified. Because of this, in 0.7.5 we made `LIKE` case-sensitive for ASCII symbols in SQLite.

Also, at this moment we don't provide LIKE operator directly in Pony. It is used for translation of Python string operations, like, `in` or `startswith`/`enswith`. These operations in Python are case-sensitive so it makes sense to keep them case-sensitive in query, so the result is the same as in Python.

In other databases, when `LIKE` operates on columns with case-insensitive collation, it provides case-insensitive result. But in SQLite the function that implements `LIKE` operator does not receive information about collations of its arguments, so it is not possible for `LIKE` in SQLite to be case-insensitive only when it is necessary.

I think we can add direct support of `like` and `ilike` (case-insensitive like) functions to Pony, so instead of
```python
select(p for p in Person if p.name.startswith("John"))
```
you will be able to explicitly write:
```python
select(p for p in Person if ilike('John%', p.name))
```

Also, in principle we can add `case_insensitive=True` option to attributes, so Pony will automatically use `ILIKE` instead of `LIKE` for columns with this option. But it may take some time to implement.

**Comment by spl0k** [comment]
> Our goal is maximum possible compatibility between different databases, so the same Pony query returns the same result in all databases.

I totally understand and that's what I would expect when working with a backend-agnostic library.
I'm also well aware that string operations are case sensitive in Python. But I chose to design my database schemas to be case insensitive on some fields, knowing it wouldn't be consistent with the Python language, for the ease of use it brings.

Adding `like` and `ilike` functions would be the same as not adding or adding `.lower()` to the operand one wants to use with `in` or `startswith`/`endswith`. Plus it would defeat the purpose of providing a pythonic way to write queries. If I wanted to use an SQL-like syntax I'd use the `raw_sql`/`select_by_sql` functions Pony is already providing us with.
I think the `case_insensitive` parameter would be more useful, especially for attributes we want to be "user-searchable". Having a single flag on an attribute is way more practical than adding the same code over and over again to every query using that attribute.

I'm aware any solution you'll come up with will take time to implement, especially since we're hitting a limitation of SQLite (compared to other database backends).
In the meantime, would you have any advice on how to globally restore the case insensitive behaviour? Is there some flag we can pass the driver when connecting to the database or any command that could be run upon connecting?

Thanks.

**Comment by kozlovsky** [comment]
In order to restore the previous behavior, you can use the following code:
```python
def ensure_case_insensitive_like(db):
    if db.provider.dialect == 'SQLite`:
        db.execute('PRAGMA case_sensitive_like = OFF')
```
You can call that funciton before each query which should use case-insensitive like, or just one time in the beginning of `db_session`.

**Comment by sashaaero** [comment]
Hi! We've made new `db.on_connect` decorator in 9dc81a5 to solve your problem and for customizing database connections with Pony. 
Example:
``` python
db = Database()

# entities declaration

@db.on_connect(provider='sqlite')
def sqlite_case_sensitivity(db, connection):
    cursor = connection.cursor()
    cursor.execute('PRAGMA case_sensitive_like = OFF')

db.bind(**options)
db.generate_mapping(create_tables=True)
```
Once you done that - every new sqlite connection will run that function and you will restore previous behavior. So you do not need to do anything inside `db_session`. 
`provider` option for `on_connect` specifies which provider will use this function. If no provider specified - function will be called for every provider. You have first positional argument `db`, you can use it to check database options to realize what to do for specific cases.
