### ISSUE TITLE
Changed behavior of QueryResult

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#369]
[This change](https://github.com/ponyorm/pony/commit/60bc463aac03e1893d0242a6ac599f8f1b7c683a#diff-a88c987cd4677b7e1918a23f4c6d0c09L5842) broke my website:

```diff
-class QueryResult(list):
+class QueryResult(object):
```

0.7.3:

```
>>> [7] + select(p for p in Person if p.age > 20)[:]
[7, Person[2], Person[3]]
```

0.7.5:

```
>>> [7] + select(p for p in Person if p.age > 20)[:]
TypeError: can only concatenate list (not "QueryResult") to list
```

If this is a bug, please fix this.

If this is a feature, please update the documentation and the changelog.

**Comment by andreymal** [comment]
There's also another case: `random.shuffle(query_result)`

Not sure if it should work by design, but it works in 0.7.3 :)

(In general, `class QueryResult` is not documented, it would be good if it will mentioned in the documentation)

**Comment by kozlovsky** [comment]
`QueryResult` now is indeed not a subclass of `list`. The reason for this change is the following: in 0.7.3, when someone write:
```
for obj in query:
    ...
```
`iter(query)` immediately fetches query result.

But now it is possible to base a new query on a previous query:
```
query2 = select(x for x in query)
```
when query is used as a source of a new generator, Python immediately takes `iter(query)` even before the `select` function is called. In 0.7.3 it forces query execution. But we don't want to execute first query, it just a part of a final query.

The solution that we use in 0.7.4 is to make query result iterator lazy, and actually execute the query only when `iterator.next` is called the first time.

That is to say, the result of `query[:]` is still fetched immediately, while `iter(query)` is lazy now. Also, `query.limit(x)` now returns query instead of a query result.

And with this changes it is more clear not to base potentially lazy `QueryResult` on `list`, but to have a separate class for it.

To fix the problem that you described we need to add 

For compatibility we can add `QueryResult.__add__` which allows adding `QueryResult` to list. But I'm against adding mutable methods `__setitem__`, `__delitem__`, `append`, `clear`, `extend`, `insert`, `pop`, `remove`, `reverse`, `sort`, because mutating query result looks strange. So, the code like `random.shuffle(query_result)` will not work. You will need to replace it with:
```
query_result = list(query_result)
random.shuffle(query_result)
```

**Comment by kozlovsky** [comment]
Now QueryResult is not based on list, but expressions like
```python
[7] + select(p for p in Person if p.age > 20)[:]
```
should work again.

Also, I added `.sort()`, `.reverse()` and  `.shuffle()` methods directly to QueryResult

For more complex mutations of QueryResult you need to convert it to list first, either with `list(query_result)`, or by calling `query_result.to_list()`
