### ISSUE TITLE
Optional attribute not working

### ISSUE THREAD

**Issue by NachoCozza** [ponyorm/pony#372]
I have defined my entity like this:

```
class CalibrationInstrument(db.Entity):
    owner = Required('Client')
    name = Required(str)
    brand = Optional(str)
    model = Optional(str)
    serial_number = Required(str)
    internal_id = Optional(str, unique=True)
    range = Optional(str)
    calibration_dates = Set('CalibrationDate')
    status = Required(str)
    is_active = Required(bool)
    PrimaryKey(serial_number, owner)
```

There are a couple of Optional attributes defined, but it doesn't work properly
When I set DB Debug to True, this is what I see when the table is created:

```
CREATE TABLE "CalibrationInstrument" (
  "owner" INTEGER NOT NULL REFERENCES "Client" ("id"),
  "name" TEXT NOT NULL,
  "brand" TEXT NOT NULL,
  "model" TEXT NOT NULL,
  "serial_number" TEXT NOT NULL,
  "internal_id" TEXT UNIQUE,
  "range" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  PRIMARY KEY ("serial_number", "owner")
)
```

This is clearly not right, as the optional fields should be defined without "NOT NULL"

I'm using Pony 0.7.5 with Python 3.6.5 and Flask 1.0

Thank you!

**Comment by kozlovsky** [comment]
This is expected behavior. "Optional" means that the attribute value can be empty, and empty string is perfectly good empty value. In most cases it is not necessary to allow NULL as a second possible empty value. Also, mixing empty string and NULL values in the same column can lead to pretty weird query results due to confusing [three-valued logic](https://en.m.wikipedia.org/wiki/Three-valued_logic) used by SQL.

But if you really want to use NULLs for string column for some specific reason, you can add `nullable=True` option to attribute:

https://docs.ponyorm.com/api_reference.html#optional-string-attributes

**Comment by NachoCozza** [comment]
Thank you! This should be better documented...
