### ISSUE TITLE
Unable to use db_session twice

### ISSUE THREAD

**Issue by martmists** [ponyorm/pony#394]
code:
```py
mod = database_handle.new_mod(**mod)  # Decorated with @db_session, returns a Mod[id]

with db_session:
    mod.authors.add(authors)
```
throws: `pony.orm.core.DatabaseSessionIsOver: Cannot change collection Mod['4975805774803820139'].authors: the database session is over`

A similar issue occurs when calling another function decorated with db_session

**Comment by sashaaero** [comment]
Hello, @martmists! 
What kind of application do you have? Is it web, gui or just script? 
Can someone else work with your database? 

It is expected behavior. 
`db_session` is the same thing as database transaction. So you can't reuse object fetched from previous transaction, since this object can be already modified or even deleted.
