### ISSUE TITLE
Generator gives TransactionError in script but works fine in shell

### ISSUE THREAD

**Issue by kulkarniniraj** [ponyorm/pony#620]
Following gives TransactionError in script when iterating over generator. But works fine in shell (ipython and notebook)
```
@db_session
def iter_data():
        qry = select(m for m in Data if m.etype == 1)
        return ((m.id, get_data(m.name)) for m in qry)

for d in iter_data():
    print(d)
```
Following works fine in script too (returning list instead of generator)
```
@db_session
def iter_data():
        qry = select(m for m in Data if m.etype == 1)
        return [(m.id, get_data(m.name)) for m in qry]
```

**Comment by sashaaero** [comment]
Hello. Can you provide a traceback of your error?

**Comment by kulkarniniraj** [comment]
```
Traceback (most recent call last):
  File "climain.py", line 35, in <module>
    run(parsed)
  File "climain.py", line 25, in run
    for (mid, data) in imgs:
  File "/home/niraj/Documents/test_inf/mediastore.py", line 70, in <genexpr>
    return Ok(((m.id, get_data(m.name)) for m in qry))
  File "/home/niraj/miniconda3/envs/tensorflow/lib/python3.7/site-packages/pony/orm/core.py", line 6292, in next
    qr._items = qr._query._actual_fetch(qr._limit, qr._offset)
  File "/home/niraj/miniconda3/envs/tensorflow/lib/python3.7/site-packages/pony/orm/core.py", line 5841, in _actual_fetch
    sql, arguments, attr_offsets, query_key = query._construct_sql_and_arguments(limit, offset)
  File "/home/niraj/miniconda3/envs/tensorflow/lib/python3.7/site-packages/pony/orm/core.py", line 5822, in _construct_sql_and_arguments
    cache = database._get_cache()
  File "/home/niraj/miniconda3/envs/tensorflow/lib/python3.7/site-packages/pony/orm/core.py", line 860, in _get_cache
    ): throw(TransactionError, 'db_session is required when working with the database')
  File "/home/niraj/miniconda3/envs/tensorflow/lib/python3.7/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.TransactionError: db_session is required when working with the database
```

**Comment by kozlovsky** [comment]
When you work in a shell, Pony automatically starts `db_session` for you to be able to execute multiple queries inside the same `db_session` without wrapping them into the `db_session` explicitly. In that case, the `db_session` applied as a decorator to the function is ignored because Pony ignores nested db sessions.

Inside a program, you must explicitly wrap queries in a `db_session` to denote transaction boundaries.

In your function
```python
@db_session
def iter_data():
        qry = select(m for m in Data if m.etype == 1)
        return ((m.id, get_data(m.name)) for m in qry)
```
The query is lazy and is not executed until you start the iteration.

So, when you then do
```python
for d in iter_data():
    print(d)
```

The query starts executing, but at this moment, the `db_session` is already over, so the query cannot be executed.

Actually, Pony currently fetches all query rows in a single action, so it is unnecessary to use a generator here. You can force fetching of query results inside a query `return [(m.id, get_data(m.name)) for m in qry.fetch()]`, or you can move `db_session` at the higher level (for example, using `with db_session:`) to include the `for` lop into the `db_session`.

**Comment by kulkarniniraj** [comment]
Got it. In my case data is only few rows, so I'll return list and work with it. Thanks.
