### ISSUE TITLE
Logging sql_debug information

### ISSUE THREAD

**Issue by gamesbrainiac** [ponyorm/pony#82]
Right now, `sql_debug` is just a function that takes in a boolean argument, `value`:

``` python
def sql_debug(value):
    global debug
    if not suppress_debug_change: debug = value
```

Would it not be better to allow a file object that allows you to log that information elsewhere instead of `sys.stdout` ?

**Comment by vincent-lg** [comment]
I would propose to open this issue again.  Not all Python users play with `loggin`.  In fact, I myself use `logbook` for one, and I don't think I'm the only one to feel like `logging`, though in the standard library, does everything that I want.  More complicated to implement, of course, but I would suggest to make the log function a hook one could replace at will.  The default behavior would remain the same, but one could conveniently change this default behavior.
As a side-note, I do replace the logging functions in Pony but that's a bit of monkey-patching and I'd rather do it through hooks, something that's easy to implement and broadly accepted (see the various `sys` hooks).  Doing it at current state is possible but since it's not suggested, it's quite possible the signature would evolve in the future and break these "unofficial hooks" with no warning.
